### ISSUE TITLE
Crashes permanently

### ISSUE THREAD

**Issue by mdebus** [piraces/rsslay#15]
Crashes with:

```
panic: interface conversion: interface {} is uint32, not int64

goroutine 35 [running]:
main.(*Relay).Init.func1()
        /app/cmd/rsslay/main.go:144 +0xac7
created by main.(*Relay).Init
        /app/cmd/rsslay/main.go:113 +0x1cd
2023/02/04 21:40:21 Running VERSION 0.3.1:
 - DSN=
 - `DB_DIR=/db/rsslay.sqlite
```

Could be a Pleroma account. Are we able to delete accounts?

**Comment by piraces** [comment]
I think the issue its located in the following block of `main.go`:

```go
last, ok := r.lastEmitted.Load(entity.URL)
if !ok || time.Unix(last.(int64), 0).Before(evt.CreatedAt) {
	_ = evt.Sign(entity.PrivateKey)
	r.updates <- evt
	r.lastEmitted.Store(entity.URL, last)
	events = append(events, replayer.EventWithPrivateKey{Event: evt, PrivateKey: entity.PrivateKey})
}
```

As you can see, we are storing the `last` variable in the original format, so when we `load` it and convert it to `int64` it may crash due to this error.

I will change the implementation to the following:
```go
last, ok := r.lastEmitted.Load(entity.URL)
if !ok || time.Unix(last.(int64), 0).Before(evt.CreatedAt) {
	_ = evt.Sign(entity.PrivateKey)
	r.updates <- evt
	r.lastEmitted.Store(entity.URL, last.(int64))
	events = append(events, replayer.EventWithPrivateKey{Event: evt, PrivateKey: entity.PrivateKey})
}
```

Storing and loading always with `int64` should resolve the problem... Nevertheless, can you share the feed causing the problem?

And also try with latest version to see if there is any problem...

**Comment by piraces** [comment]
We currently only delete accounts that are detected as invalid when processing the feed.

**Comment by mdebus** [comment]
I manually deleted the suspicious feed from the sqlite, but the crashes still ocurred. 

I'm trying 0.3.3 now, but it crashed again:
`
2023/02/05 19:27:01 checking for updates; 16 filters active
panic: interface conversion: interface {} is uint32, not int64

goroutine 5 [running]:
main.(*Relay).Init.func1()
        /app/cmd/rsslay/main.go:145 +0xb34
created by main.(*Relay).Init
        /app/cmd/rsslay/main.go:113 +0x1cd
`

**Comment by piraces** [comment]
Thanks for the info @mdebus , I'm reviewing this with priority. I will update with any progress

**Comment by piraces** [comment]
Hey @mdebus , just released a new version with a fix related with this error... Hope this solves this problem.
I think the crash came because of storing in some cases times as `uint32` and in other cases in `int64`. I'm now saving all in `uint32` and converting safely to `int64` when neccessary.

Please let me know if it still crashes for you 🙏

**Comment by mdebus** [comment]
Thanks for looking, @piraces !

Seems the uint32 problem is gone, but it stll crashes. :(

Here you go:

``` 2023/02/07 08:55:44 checking for updates; 8 filters active
panic: interface conversion: interface {} is nil, not uint32

goroutine 23 [running]:
main.(*Relay).Init.func1()
        /app/cmd/rsslay/main.go:148 +0xa46
created by main.(*Relay).Init
        /app/cmd/rsslay/main.go:113 +0x1cd 
```

**Comment by piraces** [comment]
Well it's something! Maybe with a simple null check we are ok...

Will continue debugging the problem 🤙

**Comment by piraces** [comment]
Hey @mdebus ! Sorry to bother you with this tricky bug... But I think now may be solved...

Can you try to reproduce with the latest version v0.3.5?

Thanks! 🤙

**Comment by mdebus** [comment]
Heyhey, no problem! Thanks for trying to fix this! :)

Crashed again, sorry:

```
2023/02/08 07:12:07 Running VERSION 0.3.5:
 - DSN=
 - DB_DIR=/db/rsslay.sqlite

2023/02/08 07:12:07 dsn required is not present... defaulting to DB_DIR
2023/02/08 07:12:07 database opened at /db/rsslay.sqlite
2023/02/08 07:12:07 rsslay: listening on [::]:8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5fc6bc]

goroutine 225 [running]:
net/url.validEncoded({0x0, 0xc000032808}, 0xc0003e3258?)
        /usr/local/go/src/net/url/url.go:720 +0x3c
net/url.(*URL).EscapedPath(0xc0008d8d00)
        /usr/local/go/src/net/url/url.go:698 +0x3b
net/url.(*URL).ResolveReference(0xc0008d8d00, 0xc000990d80)
        /usr/local/go/src/net/url/url.go:1110 +0x265
github.com/mmcdole/gofeed/internal/shared.(*XMLBase).push(0xc000398080, {0x0?, 0x18?})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/internal/shared/xmlbase.go:148 +0x5d
 github.com/mmcdole/gofeed/internal/shared.(*XMLBase).NextTag(0xc0006e1d40?, 0xc00057e7e0)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/internal/shared/xmlbase.go:109 +0x1a8
github.com/mmcdole/gofeed/rss.(*Parser).parseItem(0xc000014288, 0xc00057e7e0)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/rss/parser.go:330 +0x125
github.com/mmcdole/gofeed/rss.(*Parser).parseChannel(0xc000014288, 0xc00057e7e0)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/rss/parser.go:254 +0xd4c
github.com/mmcdole/gofeed/rss.(*Parser).parseRoot(0xc000014288, 0xc00057e7e0)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/rss/parser.go:67 +0x311
github.com/mmcdole/gofeed/rss.(*Parser).Parse(0xc000014288, {0xc301c0?, 0xc0004235d8?})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/rss/parser.go:28 +0xa5
github.com/mmcdole/gofeed.(*Parser).parseRSSFeed(0xc0002918f0, {0xc301c0?, 0xc0004235d8?})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/parser.go:159 +0x33
github.com/mmcdole/gofeed.(*Parser).Parse(0xc000186a20?, {0x7fe80c30f8c0?, 0xc0004d2390})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/parser.go:86 +0x1c5
github.com/mmcdole/gofeed.(*Parser).ParseURLWithContext(0xc0002918f0, {0xc00029a120?, 0x22?}, {0xc340e8?, 0xc000032040?})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/parser.go:141 +0x3de
github.com/mmcdole/gofeed.(*Parser).ParseURL(...)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/parser.go:97
github.com/piraces/rsslay/pkg/feed.ParseFeed({0xc00029a120, 0x22})
        /app/pkg/feed/feed.go:84 +0x85
main.store.QueryEvents({0xc000181500?}, 0xc00015c4e0)
        /app/cmd/rsslay/main.go:224 +0x330
github.com/fiatjaf/relayer.(*Server).handleWebsocket.func1.3({0xc00031c000, 0x13fa, 0x1500})
        /go/pkg/mod/github.com/fiatjaf/relayer@v1.7.0/handlers.go:229 +0x12bc
created by github.com/fiatjaf/relayer.(*Server).handleWebsocket.func1
        /go/pkg/mod/github.com/fiatjaf/relayer@v1.7.0/handlers.go:109 +0x46a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5fc6bc]

goroutine 117 [running]:
net/url.validEncoded({0x0, 0xc000032808}, 0xc0006b5258?)
        /usr/local/go/src/net/url/url.go:720 +0x3c
net/url.(*URL).EscapedPath(0xc0008d8d00)
        /usr/local/go/src/net/url/url.go:698 +0x3b
net/url.(*URL).ResolveReference(0xc0008d8d00, 0xc000928240)
        /usr/local/go/src/net/url/url.go:1110 +0x265
github.com/mmcdole/gofeed/internal/shared.(*XMLBase).push(0xc000398080, {0x0?, 0x7fe833a67f18?})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/internal/shared/xmlbase.go:148 +0x5d
github.com/mmcdole/gofeed/internal/shared.(*XMLBase).NextTag(0xc00057e120?, 0xc00057e120)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/internal/shared/xmlbase.go:109 +0x1a8
github.com/mmcdole/gofeed/rss.(*Parser).parseItem(0xc000014288, 0xc00057e120)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/rss/parser.go:330 +0x125
github.com/mmcdole/gofeed/rss.(*Parser).parseChannel(0xc000014288, 0xc00057e120)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/rss/parser.go:254 +0xd4c
github.com/mmcdole/gofeed/rss.(*Parser).parseRoot(0xc000014288, 0xc00057e120)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/rss/parser.go:67 +0x311
github.com/mmcdole/gofeed/rss.(*Parser).Parse(0xc000014288, {0xc301c0?, 0xc000592000?})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/rss/parser.go:28 +0xa5
github.com/mmcdole/gofeed.(*Parser).parseRSSFeed(0xc0002918f0, {0xc301c0?, 0xc000592000?})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/parser.go:159 +0x33
github.com/mmcdole/gofeed.(*Parser).Parse(0xc000186a20?, {0x7fe80c30f8c0?, 0xc0006f8fc0})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/parser.go:86 +0x1c5
github.com/mmcdole/gofeed.(*Parser).ParseURLWithContext(0xc0002918f0, {0xc0003c4a20?, 0x22?}, {0xc340e8?, 0xc000032040?})
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/parser.go:141 +0x3de
github.com/mmcdole/gofeed.(*Parser).ParseURL(...)
        /go/pkg/mod/github.com/mmcdole/gofeed@v1.2.0/parser.go:97
github.com/piraces/rsslay/pkg/feed.ParseFeed({0xc0003c4a20, 0x22})
        /app/pkg/feed/feed.go:84 +0x85
main.store.QueryEvents({0xc000280000?}, 0xc00015c1a0)
        /app/cmd/rsslay/main.go:224 +0x330
github.com/fiatjaf/relayer.(*Server).handleWebsocket.func1.3({0xc00031ea00, 0x13fa, 0x1500})
        /go/pkg/mod/github.com/fiatjaf/relayer@v1.7.0/handlers.go:229 +0x12bc
created by github.com/fiatjaf/relayer.(*Server).handleWebsocket.func1
        /go/pkg/mod/github.com/fiatjaf/relayer@v1.7.0/handlers.go:109 +0x46a
```

**Comment by piraces** [comment]
Ohh... I think I should try to reproduce the bug via tests and then fix it... I have been doing hotfixes before and I don't think is the correct way. I will try to do as soon as possible 🤙

**Comment by piraces** [comment]
Hey @mdebus , it's there any chance you could pass me the links you have in your database? I'm finding it hard to reproduce this bug... Nevertheless, I'm working in increasing the test coverage and others. There is a new version v0.4.0 if you want to try it out also...

**Comment by mdebus** [comment]
Have a look here: https://rsslay.data.haus

It didn't crash in the last 24 hours. Maybe the last version fixed it.

BTW: 0.4.0 docker shows 0.3.6 as version.

**Comment by piraces** [comment]
Awesome! Let's keep this issue open then to keep track of the issue and I will try to keep focusing on stability 🤙

**Comment by piraces** [comment]
Closing this due to inactivity... I cannot reproduce the problem but if keeps happening please feel free to reopen this issue or comment in it @mdebus 🤙
